### ISSUE TITLE
矢印を描画したと同時に，矢印ラベルのテキストボックスを出現させる

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#1]

**Comment by yoheiMune** [comment]
現状まだ直線ではありますが、矢印描画後にテキストボックスを表示するように実装をしました。
使い勝手のイメージがあっているかご確認お願いできますでしょうか？
http://pdf-anno.paint-ink.com/pages/viewer.html

また、以下の点も修正してあります。
・線の太さを細くしました。
・テキスト入力の終了判定から「Enterキー押下」を削除（日本語入力に対応するため）。
・テキストサイズの変更（16→12px）。

よろしくお願いします。

**Comment by hshindo** [comment]
合っています．これで問題ありません．

**Comment by yoheiMune** [comment]
早速のご確認ありがとうございます。
（Issueでのコミュニケーションもやりやすくていいですね！）

それでは続いて#2の対応に進みます。
引き続きよろしくお願いします。
