### ISSUE TITLE
マウス右上→左下でもRectを作れるようにする

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#10]
現在のRectツールは，マウスのドラッグによって，長方形の左上を始点として，右下を終点とするRectを描画できるようになっています．
したがって，始点よりも終点を左にすることはできません．

実際には，長方形の右上を始点として，左下を終点とするようなRectを描画したい場合もあるので，現在の実装を拡張して，始点から右方向へも左方向へもドラッグでRectを描画できるようにしたいと思います．

始点と終点が垂直になった場合には，Rectは描画されないようにしてください．

**Comment by hshindo** [comment]
【追加】同様に，rectの右下や左下を始点にして，右上や左上を終点にすることもできると思いますので，そのようにお願い致します．

**Comment by yoheiMune** [comment]
上記の追加内容も了解いたしました。

**Comment by yoheiMune** [comment]
お世話になっております。
Rectの描画を上下左右どちらにもできるように修正しました。
http://pdf-anno.paint-ink.com/pages/viewer.html

ご確認よろしくお願いいたします。

**Comment by hshindo** [comment]
確認しました．問題なさそうです．
有難うございました．

**Comment by yoheiMune** [comment]
ご確認ありがとうございました。
