### ISSUE TITLE
矢印の種類（片方向，双方向）

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#14]
矢印の種類を，片方向と双方向から選べるようにする．
UIは今後検討する．

**Comment by yoheiMune** [comment]
UI案ですが、以下はいかがでしょうか？
現在のarrowツールボタンについて、クリックごとに以下の状態遷移を行う。
　・1回押すと現在のように単方向
　・2回目押すと双方向
　・3回目押すと描画モード解除（閲覧モードになる）

このUIの場合、双方向にする方法が初見ではわかりづらいですが、UI自体はスッキリする（ボタン1つで良い）ので良いのではないかと思います。初見ではわかりづらい点も、今後デザインを工夫すれば解決するかと思います。

ご検討いただけましたら幸いです。

**Comment by hshindo** [comment]
はい，ひとまず上記の方法でお願いします．
矢印の種類が単方向，双方向の２種類だけでＯＫかどうか，少し検討させてください．
もう少し種類が増えるとなると，矢印ボタンを拡張するような形になるかと思います．

**Comment by yoheiMune** [comment]
了解いたしました、ご確認ありがとうございます。
矢印の種類が増える場合には、またその時にお申し付けください。
上記の内容にて実装を進めます。

**Comment by yoheiMune** [comment]
お世話になっております。
単方向/双方向の矢印について実装しました。
http://pdf-anno.paint-ink.com/pages/viewer.html

お手隙の際にイメージに合っているかご確認お願いできますでしょうか？
よろしくお願いします。

**Comment by hshindo** [comment]
はい，これで問題ありません．
有難うございます．

**Comment by yoheiMune** [comment]
ご確認ありがとうございました。
