### ISSUE TITLE
Webページの作成

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#15]
案：
ページ左側（サイドバー）にファイル指定やツールボックスを置く．
ページ右側に，div要素としてpdf.jsを埋め込む．
全体イメージは，簡単なものをまず私がアップロードします．

* pdf.jsのメニューバーを削除　→　Webページのサイドバーへ移動
* pdf.jsをソースコードから削除．代わりに[CDN](https://cdnjs.com/libraries/pdf.js)から取得（？）

アイコン：
* http://fontawesome.io/icons/

* Cleanアイコン： https://github.com/FortAwesome/Font-Awesome/issues/239

**Comment by yoheiMune** [comment]
了解致しました。
お手数おかけしますがイメージよろしくお願いします。

**Comment by hshindo** [comment]
こちらへ置きました．
https://paperanno.github.io/paperanno/

**Comment by hshindo** [comment]
実体は，https://github.com/paperanno/paperanno
のdocs/index.htmlです．

**Comment by yoheiMune** [comment]
ありがとうございます、確認して対応します。

**Comment by hshindo** [comment]
このindex.htmｌをpdfannoの方へコピーして，適宜修正していただけないでしょうか？

最終的には，htmlannoと統合してpaperannoという名前にする予定ですが，もうしばらくは，pdfanno単体で開発したいと思っています．

基本はbootstrapで，iconはawesome fontというものを使っています．

**Comment by hshindo** [comment]
左右分割よりも上下分割の方が良さそうなので，そのようなレイアウトにしてあります．

**Comment by yoheiMune** [comment]
諸処了解致しました。
1点質問なのですが、現在のデモページの上部で表示しているツールバー（拡大指定や印刷ボタンなど）はなしにして、今回の機能のみを利用できる状態にするという認識であっていますでしょうか？

**Comment by hshindo** [comment]
拡大・縮小や印刷ボタンはそのままにしておきたいと思います．
firefoxのデフォルトのpdf viewerと同じものが出てきた方がユーザーにとって馴染みがあると思いますので．

**Comment by hshindo** [comment]
イメージとしては，以下のような感じです．
http://www.cnergres.iitkgp.ac.in/OCR%2B%2B/home/

**Comment by yoheiMune** [comment]
イメージ了解しました。
ありがとうございます！

**Comment by yoheiMune** [comment]
お世話になっております。
作業途中となりますが進捗のご報告をさせて頂きます。
下記のようにpdf.jsを埋め込みました。このようなイメージであっていますでしょうか？
http://pdf-anno.paint-ink.com/dist/

まだ各種機能のつなぎこみをしていない（またpdf.jsからアノテーション付与のツールバーを削除していない）ので動かないところですが、イメージの共有だけでもさせて頂けたらと思います。

引き続き実装を進めます。
よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．
はい，これで問題ありません．
よろしくお願いします．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
引き続きどうぞよろしくお願いします。

**Comment by yoheiMune** [comment]
お世話になっております。
Secondary Annotation以外の部分を実装しました。
また、ボタン名など「Upload」に修正しました。
ご確認頂けますと幸いです。
http://pdf-anno.paint-ink.com

また、以下機能を暫定的に追加しています。見た目などご要望仰って頂けたらと思います。
◆DL
ダウンロードできる機能がなかったので勝手ながら追加しています。
◆DEL
アノテーションを削除できる機能がなかったので、勝手ながら追加しています。

続いて、SecondayAnnotationの実装を行います（こちらは #17のチケットで対応とさせてください）。
どうぞ宜しくお願いします。

**Comment by hshindo** [comment]
選択モードが正常に動作していないように見えますが，いかがでしょうか？
一番左のアイコンを選択した場合です．

**Comment by yoheiMune** [comment]
すみません、確認します。

**Comment by hshindo** [comment]
DLアイコンは，fa-downloadに変更していただけますか？

**Comment by hshindo** [comment]
アノテーションを行ったあと，一回ブラウザをreloadすれば，選択モードが正常に動作するみたいです．

**Comment by hshindo** [comment]
DL, DELアイコンは，それぞれ独立に動作するものだと思いますので，
index.htmlで，DL, DELは"btn-group"タグの外に出していただけますか？

**Comment by yoheiMune** [comment]
不具合あり申し訳ありません、以下3点修正しました。
http://pdf-anno.paint-ink.com/dist/index.html

* アノテーション追加後に選択モードが動作しない
* DL, DELアイコンは、それぞれ独立にした（btn-groupの件）
* DLアイコンをfa-downloadに変更

お手隙の際にご確認頂けたら幸いです。
宜しくお願いします。

**Comment by hshindo** [comment]
有難うございます．３点確認しました．これでＯＫです．

選択モードで，矢印ラベルをダブルクリックすると，テキストを編集できるようになっていたはずですが，この機能が上手く働いていない場合があります．ご確認いただけないでしょうか？

**Comment by yoheiMune** [comment]
お世話になっております。
矢印ラベルの編集処理で不具合があり申し訳ありません。ダブルクリック時の挙動について修正を致しました。ご確認お願いできますでしょうか？
どうぞ宜しくお願いします。

**Comment by hshindo** [comment]
確認致しました．
これで問題なさそうです．有難うございます．

**Comment by hshindo** [comment]
pdf.jsが埋め込まれている<div id="viewer">についてですが，
今後，pdfではなくhtmlファイルを指定したときは，pdf.jsの代わりにhtmlannoを読み込むようにする予定ですが，可能でしょうか？

**Comment by hshindo** [comment]
または，Webページそのものをpdfとhtmlで分けることも考えられると思いますが，いかがでしょうか？

**Comment by yoheiMune** [comment]
現状の作りですと、pdf.jsの読み込みはiframe（下記ソースコード）で読み込んでいて、iframeのsrc先を変更すれば別のソース（htmlannoなど）も読み込みすることができます。
https://github.com/pdfanno/pdfanno/blob/master/src/index.html#L80

ただ、fileloadやアノテーションボタンの制御などは以下で書いていて、pdf-annotate.jsを操作する処理が多数ありますので、htmlannoの時には別ファイルを用意することが良いと思います。
https://github.com/pdfanno/pdfanno/blob/master/src/app.js

> または，Webページそのものをpdfとhtmlで分けることも考えられると思いますが，いかがでしょうか？

作業者が2人ということもありますので、別のhtmlで開発した方がスムーズかなと個人的には感じます。

ご参考になりそうでしょうか？

**Comment by hshindo** [comment]
有難うございます．
では，別ページにしたいと思います．
こちらでWebページの更新などは行います．

今後の進め方ですが，どこかのタイミングで，paperannoのリポジトリに，現在のpdfannoをコピーして置きます．
そこから先は，paperannoをpdf側とhtml側でそれぞれフォークするなどして別々に作業　→　プルリクエスト＆マージ
という形でも良いでしょうか？

**Comment by hshindo** [comment]
単にpaperannoのブランチを分けて，pdf, htmlそれぞれで開発　→　マージという形で良いかもしれません．

**Comment by hshindo** [comment]
全体のWebページと，スタイルファイル，jsなどをpdf, htmlで共有したいことが増えてきたタイミングで統合する予定なので，もうしばらくはこのまま別々で良いかもしれません．

**Comment by yoheiMune** [comment]
レポジトリのお引越しの件、了解しました。

> 単にpaperannoのブランチを分けて，pdf, htmlそれぞれで開発　→　マージという形で良いかもしれません．

そうですね、できれば同じレポジトリ内の別ブランチで作業させて頂いた方が作りやすいので、そうさせて頂けると助かります。

引き続きどうぞ宜しくお願いします。

**Comment by yoheiMune** [comment]
あっ、了解です！
統合のタイミングはいつでも大丈夫です。

確認ありがとうございました。

**Comment by hshindo** [comment]
現在のデモをこちらでも動かしたいのですが，READMEを更新していただけませんか？
viewer, viewer2などは不要であれば削除して，READMEも更新をお願いします．

**Comment by yoheiMune** [comment]
お世話になっております。
取り急ぎREAMEを更新し、ビルド方法やローカル環境での開発方法の記載を修正しました。
https://github.com/pdfanno/pdfanno/

ディレクトリ整理はこれから行います。
よろしくお願いします。

**Comment by yoheiMune** [comment]
お世話になっております。
レポジトリ以下のファイルの整理も行い、不要なものは全て削除しました。
https://github.com/pdfanno/pdfanno

こちらの内容にてお引越しできればと思います。
よろしくお願いします。

**Comment by hshindo** [comment]
ありがとうごさいます。
確認して、私のほうで移行します。

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
よろしくお願いします。

**Comment by hshindo** [comment]
build以下のpdf.js, pdf.worker.jsは，外部から取得する形にすることは可能でしょうか？

**Comment by hshindo** [comment]
それとも，ここに置いておくほうが良いでしょうか？

**Comment by yoheiMune** [comment]
上の2つはbuild以下に置いて貰えますでしょうか？
別ドメインにすると取得できなくなってしまうためです。
よろしくお願いします。

**Comment by hshindo** [comment]
わかりました．

**Comment by hshindo** [comment]
pages以下にあるのは，pdf.jsのviewerでしょうか？
これも必要でしょうか？

**Comment by hshindo** [comment]
pdf.jsだと，locale，cmapsなどはgitignoreに設定されているようです．
https://github.com/mozilla/pdf.js/blob/a7c35025fed8beb8f9b93688fff40497c7ad2de0/web/.gitignore

もし何かご存じでしたら，教えていただけると助かります．

**Comment by yoheiMune** [comment]
pagesフォルダ以下にあるものはビュワーのUI表現（Firefoxで使っているＵＩ）に必要なものですが、詳細は今日の夜に確認して返信します。

2016/12/03 午後4:51 "Hiroyuki Shindo" <notifications@github.com>:

**Comment by hshindo** [comment]
有難うございます．
ここにあまり時間を使ってもしょうがないので，ひとまずこのまま移行します．

**Comment by yoheiMune** [comment]
了解致しました！
