### ISSUE TITLE
アノテーション要素を選択時の表示変更

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#16]
現在は，アノテーション要素のアクティブ時・選択時を主に色の変化として表現しているが，色の変化を用いない表示へ変更する．

理由：　この後，複数のアノテーションファイルを重ね合わせて表示させる機能（multi-user機能）を追加するので，ユーザーの違いを色の変化で表現するため．

これに合わせて，上記の機能について，htmlannoと共有できるもの（css, jsファイル）は共通化する．
* https://github.com/pdfanno/htmlanno

**Comment by yoheiMune** [comment]
了解致しました。おおよそhtmlannoのソースコードは確認しました。
部品やコードを再利用しながら進めます。

**Comment by hshindo** [comment]
html, pdfともに，なるべく同じ操作感にしたいと思いますので，共有化できる部分（css, js）を別ファイルとして切り出して，それを使うようにしていただけないでしょうか．
htmlannoも，それに合わせてコードを変更したいと思います．

アノテーション要素のアクティブ時，選択時の表示に関しては，htmlannoのように色でない変化を使うようにしたいと思います．

現在のところ，
* ハイライト：　htmlannoと同じような表示にする．すなわち，
  * マウスオーバー時：　左上の○を少し大きくなる
  * 選択時：　ハイライト領域の枠線を黒の点線になる
* 矢印：　htmlannoと同じような表示にする．すなわち，
  * マウスオーバー時：　矢印が少し大きく（太く）なる
  * 選択時：　矢印の枠線が黒の点線になる

**Comment by yoheiMune** [comment]
了解致しました。htmlannoでは操作感についてCSSで指定しているようですので、それをpdfannoでも利用することが可能と思います。

ただJSについては、htmlannoはjQueryベース、pdfannoはpdf-annotate.jsベース(=svgを多用)で利用技術が違い共通化が難しいかもしれません。

ここはご相談なのですが、今後も色々と機能追加することを考えると、今のうちにpdfannoもjQueryベースに書き換えた方が将来的には幸せかもしれません。利用技術もできるだけ合わせていった方がよろしいでしょうか？（個人的にはpdf-annotate.jsベースよりもjQueryベースの方がコードも少なくて良い印象を受けます）。

**Comment by hshindo** [comment]
はい，jqueryベースのほうが良さそうです．
ただ，先にマルチユーザーなどの部分を実装したいので，共通化の部分は後回しでも良いでしょうか？
一通り機能が揃ってから，細かい部分を修正していきたいと思います．

**Comment by yoheiMune** [comment]
ご意向了解致しました。
それでは一旦は今の技術要素で実装を進めます。
よろしくお願いします。

**Comment by hshindo** [comment]
それとも，先にjqueryへ移行する部分をやってしまったほうが，効率が良いでしょうか？
マルチユーザー機能までの実装が一区切りだと考えていますので，そこに至るまでの順序はおまかせします．

**Comment by yoheiMune** [comment]
あっいえ、一旦マルチユーザー機能までは現行のところで開発を進めます。
といってもjQueryは今からでも導入できますので、随時、jQueryの方が実装が速いところはそっちにしていきます。
よろしくお願いします。

**Comment by hshindo** [comment]
はい，ではそのようなやり方でよろしくお願いします．

**Comment by yoheiMune** [comment]
お世話になっております。
すみません別件で緊急対応がありましたので少し着手が遅くなってしまいました。
申し訳ありません。

途中経過となりますが、マウスオーバー時の表示を実装しました。
このイメージで問題ないかご確認お願いできますでしょうか？
http://pdf-anno.paint-ink.com/pages/viewer.html

実装としても、htmlannoで実装してある以下のCSSを転用して使うようにしています（表示切り替えの実装自体はhtmlannoとpdfannoでまだ異なります）。また、htmlannoに合わせた方が実装がシンプルになる箇所もあるので実装を進めながら修正していきます。
https://github.com/pdfanno/htmlanno/blob/master/public/index.css

これからクリック時の動作も実装します（現在はハイライトのみ実装しています）。
どうぞよろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．これでOKです．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
認識があっていて良かったです。

**Comment by yoheiMune** [comment]
お世話になっております。
クリック時の挙動についても実装を行いました。
こちらで問題ないかご確認お願いできますでしょうか？
http://pdf-anno.paint-ink.com/pages/viewer.html

クリック時の動作もhtmlannoを参考に実装を合わせております（主にCSS部分）。
よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．これで問題ないと思います．

**Comment by yoheiMune** [comment]
ご確認ありがとうございました。
