### ISSUE TITLE
複数のアノテーションファイルを同時に描画

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#17]
同じＰＤＦに対して複数のアノテーションファイルが指定されたとき，色を変えて重ね合わせる．

**Comment by yoheiMune** [comment]
了解致しました。1点ご質問させてください。

> 複数のアノテーションファイルが

こちらですが、アノテーションファイルが同一のものか異なるものかについて、どのような判定基準にすればよろしいでしょうか？おそらくユーザー毎に一意?にする形かなと考えていますが、その場合には最終的にはサーバーでCookieなどでユーザーを識別する仕組み（そしてそのCookieの値をアノテーションファイルにも入れる）ようなイメージなどでしょうか？？

**Comment by hshindo** [comment]
現在のところ，
* primaryのアノテーションファイル（１つ）
* secondaryなアノテーションファイル（オプショナル，複数）
という形で指定できるようにする予定です．

primaryなものは，通常は自分のannoファイルを指定します．今までと同じように，pdf.js上で編集できます．
secondaryなものは，通常は他人のannoファイルです．readonlyな要素としてPDF上にレンダリングされます．


アノテーションファイルが同一のものか判断する，というのはどのようなcaseで必要でしょうか？

**Comment by yoheiMune** [comment]
すみません僕がただ理解していないだけなのかもしれないのですが例えば、以下2つのファイルがある場合って2つをアップロードされた場合に、
 * 1.pdfanno
 * 2.pdfanno  

プログラムとしては、どっちがユーザーのファイルで、どっちが他人のファイルなのかをどうやって判別すべきかと思いまして・・。

例えばユースケースとしては、
「よし、昨日編集した自分のファイル(1.pdfanno)をロードして、他人の(2.pdfanno)もロードしよう」という場合（つまり、1.pdfanno → 2.pdfannoの順にロード）と、

「よし、他人の(2.pdfanno)もロードして、あとは自分が編集しているファイル(1.pdfanno)をロードしよう」という場合（つまり、2.pdfanno → 1.pdfannoの順にロード）

とで、どのように自分のファイルと他人のファイルを認識し分けようかと思いました。

ただ書いていて思ったのですが「自分用」と「他人用」でロードする際に指定する（またはそれぞれをロードするためのUIがある）ので解決しますね。。

失礼いたしました。
ユースケースについて了解いたしました！

**Comment by hshindo** [comment]
はい，annoファイルをD&Dするテキストボックスは，primary, secondaryの２つを用意しますので，それで判別できます．
よろしくお願い致します．

**Comment by yoheiMune** [comment]
了解致しました。
ありがとうございます。
