### ISSUE TITLE
paperai/paperannoへの移行

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#18]
https://github.com/paperai/paperanno
https://github.com/paperai/paperanno-ja

* paperannoにpdf, htmlのbranchを作って作業する．commitメッセージなどは英語で行う．
* 日本語で行う議論，issueなどは，paperanno-jaで行う．

**Comment by hshindo** [comment]
現在のpdfannoで，不要な部分は削除して整理していただけないでしょうか？
具体的には，pagesディレクトリ，srcディレクトリです．

**Comment by yoheiMune** [comment]
返信遅くなり申し訳ありません。了解しました。

**Comment by hshindo** [comment]
移行しました．
適当にブランチを作って，そちらで作業していただければと思います．
コミットメッセージは英語でお願いできるでしょうか．

issueに関する議論は今まで通り日本語で行いたいと思いますので，paperanno-jaのほうに移行します．
