### ISSUE TITLE
Rectの表示位置が左上にずれる

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#3]
Rect機能のアノテーションですが，マウスでドラッグしている最中の長方形の表示（ブルー）に対して，実際にマウスドロップした後に表示される長方形（レッド）の位置がやや左上にずれてしまいます．

以下，例です．

![sample1](https://cloud.githubusercontent.com/assets/6833527/19392111/5a231bdc-926a-11e6-8d10-62c2d50d801a.png)

![sample2](https://cloud.githubusercontent.com/assets/6833527/19392115/5de1b3a0-926a-11e6-84d4-a334e0a61206.png)

**Comment by yoheiMune** [comment]
おはようございます。
こちらの不具合を修正し、以下にアップしました。
http://pdf-anno.paint-ink.com/pages/viewer.html

お手隙の際にご確認いただけましたら幸いです。
よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．修正を確認致しました．
赤線の太さをもう少し細くできますか？青い線と同じ太さでちょうどよいです．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
了解しました、調整します！

**Comment by yoheiMune** [comment]
@hshindo お世話になっております。
対応が遅くなり申し訳ございません。赤線の太さを調整いたしました。
お手隙の際にご確認よろしくお願いします。
http://pdf-anno.paint-ink.com/pages/viewer.html

**Comment by hshindo** [comment]
確認しました．問題ありません．有難うございました．
