### ISSUE TITLE
Arrowを曲線にする

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#4]
操作感，曲線の具合は，以下のような感じを想定しています．
WebAnnoというツールをキャプチャしました．
矢印も，このくらいの線の太さで丁度良いと思います．

![arrow](https://cloud.githubusercontent.com/assets/6833527/19418600/3bfea29a-9402-11e6-84fb-d5ae529f868d.gif)

**Comment by yoheiMune** [comment]
お世話になっております。
曲線の実装を行いました。まだコメント入力欄の位置調整がありますが、「操作感」と「曲線の具合」をご確認いただくことは可能でしょうか？上記サンプルに極力合わせるようにはしましたが、ご都合の良い感じをご指摘いただけますと幸いです。
http://pdf-anno.paint-ink.com/pages/viewer.html

よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．
１点気になった部分は，曲線の弧（傾き）が大きく切り替わるポイントがあり，そこを滑らかにしたいのですが，可能でしょうか？WebAnnoでは，マウスを上下左右に動かしても曲線の弧は滑らかに切り替わります．

下記アニメーションで，マウスを上下に往復させている部分です．

![sample](https://cloud.githubusercontent.com/assets/6833527/19618355/058c3eae-9883-11e6-9eb3-938c72fcd784.gif)

**Comment by hshindo** [comment]
曲線の曲がり具合の計算は，単純なアルゴリズムで構いません．

あくまでも一例ですが，
まず，始点と終点が垂直線上に位置していた場合は，直線で良いです．（図のＡ，Ｅ）
水平の場合は，弧の丸みが最大になります．（図のＣ）
その中間の場合は，滑らかに遷移していくような円弧を計算します．（図のＢ，Ｄ）

![sample](https://cloud.githubusercontent.com/assets/6833527/19618499/d7e763e4-9886-11e6-9d1a-5209583d4da3.png)

**Comment by yoheiMune** [comment]
了解致しました。
曲がり具合について、少し簡易にしきい値を設けての実装にしていましたので修正します。
宜しくお願いします。

**Comment by yoheiMune** [comment]
お世話になっております。
曲がり具合についてシームレスに変わるように実装を修正しました。
このような具合でイメージと合っていますでしょうか？
http://pdf-anno.paint-ink.com/pages/viewer.html

引き続きテキストエリアの表示位置の調整を行います。
よろしくお願いします。

**Comment by yoheiMune** [comment]
（追伸です）
テキスト入力欄の位置も調整いたしました。
こちらもご確認いただけますと幸いです。
よろしくお願いします。

**Comment by hshindo** [comment]
これで問題ありません．
有難うございました．
