### ISSUE TITLE
複数行ハイライト時のマウスオーバーの修正

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#5]
矢印モードでは，ハイライト部にマウスオーバーするとハイライト部がアクティブになりますが，複数行がハイライトされているとき，ハイライト部以外の領域もアクティブになってしまいます．

<img width="721" alt="sample" src="https://cloud.githubusercontent.com/assets/6833527/19420875/a13adcd2-942f-11e6-95bc-bcb9c8099acf.png">

**Comment by yoheiMune** [comment]
お世話になっております。
こちらの不具合を修正いたしました。
http://pdf-anno.paint-ink.com/pages/viewer.html

独自に矢印を引けるエリアを表現（上の赤枠）するのではなく、ハイライト箇所へ矢印を引けるようにしました。そのため、矢印ツールを選択した際の強調表示も少し変更いたしました。

お手隙の際にご確認をお願いします。
宜しくお願いします。

**Comment by hshindo** [comment]
有難うございました．
確認致しました．これで問題ありません．
