### ISSUE TITLE
矢印アノテーションの透過処理

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#7]
矢印・矢印ラベルのアノテーションは透過処理を行って，pdf本文が完全に隠されないようにしたいと思います．
透過度は，ひとまず適当で良いです．簡単にできるでしょうか？

また，矢印，または矢印ラベルをマウスオーバーすると，矢印とラベルがアクティブになって，透過表示でなくなる（つまり，pdf本文より優先して前面に表示される）ようにしたいと考えています．

**Comment by hshindo** [comment]
イメージです．（色は適当です）

* 矢印・矢印ラベルがアクティブでないとき：
![sample](https://cloud.githubusercontent.com/assets/6833527/19621075/0993b6b6-98c5-11e6-9a4d-4cf3de4dd8e1.png)

* アクティブのとき：
![sample2](https://cloud.githubusercontent.com/assets/6833527/19621077/1324d8e0-98c5-11e6-8b8c-42d5615cd62c.png)

**Comment by hshindo** [comment]
ラベルがアクティブになるときは，始点と終点のハイライトも同時にアクティブになる，という実装で良いと思います．

**Comment by yoheiMune** [comment]
お世話になっております。
こちらの対応が遅くなっており申し訳ありません。進捗のご報告をさせていただきます。

こちらのIssueですが、マウスオーバーレイにおける要素のヒット判定、ラベルの背景色、ベジエ曲線でのヒット判定など少し実装内容が多く時間がかかっております。すみません。
今週中にはお見せできる形にできればと思います。

すみませんが、宜しくお願いします。

**Comment by hshindo** [comment]
ありがとうございます。
技術的に困難な点があれば、後回しで結構です。
単に実装に少し時間がかかるだけならば、引き続きこのissueをお願いします。

**Comment by yoheiMune** [comment]
了解いたしました、ご配慮ありがとうございます。
こちらのIssue対応を引き続き行います。
宜しくお願いします。

**Comment by hshindo** [comment]
現在，pdfではなく，htmlのアノテーションツールも平行して開発しています．
１つの案ですが，
https://github.com/pdfanno/htmlanno/issues/5

このように，ハイライトがオーバーラップする場合がありうるので，現在のようにハイライト領域全体に対してマウスオーバーのヒット判定をしてしまうと，同じ座標に対して複数のハイライトが該当してしまうという問題があります．

そこで，ハイライト領域の左上に○印をつけておいて，ここをマウスオーバーするとアクティブになる，というようにするのはどうかと考えています．

もしそのようにするならば，矢印の中央付近にも同様に○印をつけておいて，そこをマウスオーバーすると矢印がアクティブになる，という動作になると思います．
この場合，ベジェ曲線全体の領域に対するヒット判定が不要になり，○印の部分のみがマウスオーバーされるか監視していれば良いということになると思うので，実装が簡単になるでしょうか？

**Comment by yoheiMune** [comment]
お世話になっております。HTML版も開発中なんですね！
おお、なるほど了解いたしました。ベジエ以外は実装済みで、ベジエ曲線についても始点/終点/制御点の3点からなる三角形での内外判定にすることで、実装を簡易に行っていました。

上記の内容について1点確認させてください。
「重なったハイライトがあった場合に、複数が強調表示されるのは困る、（ユーザーが選んだ）1つだけを強調をしたい」という問題になりますでしょうか？

ご提案頂いた内容で実装可能ですので、実装してみますね。

**Comment by hshindo** [comment]
ハイライトを強調表示する理由の１つは，そこから矢印を引っ張る始点を決定するためなので，複数のハイライトが同時に強調されてしまうと，どのハイライトから矢印を弾くのか同定できない，という問題があります．
そのため，強調，選択は必ず１つにしたいと思います．

HTMLのほうと共有化できる部分もあると思いますので，そのあたりは適宜ご相談させてください．
現在は，ひとまず別々に作成している状況です．
よろしくお願いします．

**Comment by yoheiMune** [comment]
現状実装している内容をサーバーにアップしました。
（アノテーション保存内容を変更しているので）新規にハイライトや矢印や文字をアノテーション付与頂いた後に、閲覧モード（編集しないモード）にしていただくと、マウスの動きに応じて強調表示を行います。ベジエ曲線部分は未実装です。
http://pdf-anno.paint-ink.com/pages/viewer.html

大変申しわけありません、上記仕様についてもう少し質問をさせてください。
上記のユースケースですが、編集（矢印を引く）時に限定した内容になりますでしょうか？
例えばこのIssueのマウスオーバーによる強調表示の場合（=閲覧モードの場合）は、マウスの下に複数のハイライトがあれば、それら全てを強調表示するというイメージでしょうか？

> そこで，ハイライト領域の左上に○印をつけておいて，ここをマウスオーバーするとアクティブになる，というようにするのはどうかと考えています．
> もしそのようにするならば，矢印の中央付近，または矢印ラベルの左上付近にも同様に○印をつけておいて，そこをマウスオーバーすると矢印がアクティブになる，という動作になると思います．
> この場合，ベジェ曲線全体の領域に対するヒット判定が不要になり，○印の部分のみがマウスオーバーされるか監視していれば良いということになると思うので，実装が簡単になるでしょうか？
こちらの記載内容だと、「◯印」は常に表示して、閲覧/編集モード両方で使うとなりますでしょうか・・・？

理解ができておらず申し訳ございません。
すみませんが宜しくお願いします。

**Comment by hshindo** [comment]
すみません，少しわかりにくかったかもしれません．
> こちらの記載内容だと、「◯印」は常に表示して、閲覧/編集モード両方で使うとなりますでしょうか・・・？
はい．

どのモードであっても，ハイライトのボックス領域内で，マウスオーバーやクリック動作を行っても何も起こらず，
そのようなイベントは全て，左上の○印の領域のみに集約するということです．

したがって，閲覧時でも編集時でも，常に○印があって，そこをマウスオーバーすると，１つのハイライト領域がアクティブになったり，そこから矢印を弾くことができます．

何か問題がありそうであれば，お知らせください．

**Comment by yoheiMune** [comment]
なるほど、了解しました！
1点ご相談なのですが、 要素の活性/非活性はクリックでもよろしいでしょうか？ #5のような複数行のハイライトの場合に、マウスオーバーだと左側の領域から矢印を引けないためです。
こちらはいかがでしょうか？

**Comment by hshindo** [comment]
> マウスオーバーだと左側の領域から矢印を引けないためです。

すみません，この部分はどういう意味でしょうか？

**Comment by hshindo** [comment]
デモ確認致しました．おおよそイメージ通りです．

矢印ラベルのテキストボックスですが，テキストボックスの枠とテキスト間の余白が多いので，それを削っていただけないでしょうか？

**Comment by yoheiMune** [comment]
すみません、失礼致しました。
#5のような1つのハイライトが複数行にある場合に、ハイライト始点の上にある○印にマウスオーバーすると該当の複数行のハイライトが選択状態になると思いますが、その状態で左側のハイライトエリアにマウスを持っていくと、移動途中にハイライトからマウスが外れてしまい、選択状態が解除されてしまう。その結果、（選択状態出ないので）矢印の始点にできず線が引けない、という内容です。

分かりづらい内容で申し訳ございません。

細かい点ですので、実装させて頂きながら最適な方法を探すのでも大丈夫です。

ご検討頂けましたら幸いです。よろしくお願いします。

**Comment by yoheiMune** [comment]
テキスト枠の余白了解です。
現在余白は10pxにしていますが、小さくします！

**Comment by hshindo** [comment]
なるほど，（おそらく）意味がわかりました．

○印をマウスオーバーして，そのままハイライトの長方形領域内にマウスを移動させて，そこから矢印の始点を開始する，という操作を想定されているでしょうか？

もしそうならば，これは矢印の始点と終点をユーザーが選択できるようにするかどうか，という問題になるかと思います．

そうではなくて，必ず○印から○印を矢印でつなぐことにするならば，このような問題は起きないのではないかと考えていますが，いかがでしょうか？
ただし，この場合には，左上のハイライトから右下のハイライトへ矢印を弾くと，矢印の線と左上のハイライトが重なってしまうので見にくいかもしれません．

ひとまず，クリックでアクティブ，非アクティブを切り替える，という実装でも構いません．
よろしくお願いします．

**Comment by hshindo** [comment]
![sample](https://cloud.githubusercontent.com/assets/6833527/19828425/46cc1600-9e00-11e6-83bb-37612512c6dc.png)

**Comment by yoheiMune** [comment]
図までありがとうございます！
arrowの始点終点をユーザーが選べるようにする実装はすでにできておりますので、それを使う方法でも上記の○印を結ぶ方法でもどちらでも問題ございません。
一旦は、上記でいただいている○印間を結ぶように実装して進めます。やっぱり見づらいとなりましたら、その際には修正させていただけたらと思います。また実装中に改善点がありましたら、都度ご相談させてください。
宜しくお願いします！

**Comment by hshindo** [comment]
わかりました．ひとまず○印間を結ぶことにしようと思います．
その場合，
> #5のような1つのハイライトが複数行にある場合に、ハイライト始点の上にある○印にマウスオーバーすると該当の複数行のハイライトが選択状態になると思いますが、その状態で左側のハイライトエリアにマウスを持っていくと、移動途中にハイライトからマウスが外れてしまい、選択状態が解除されてしまう。その結果、（選択状態出ないので）矢印の始点にできず線が引けない

この問題は起こらない，と認識していますが，合っているでしょうか？

**Comment by yoheiMune** [comment]
はい、○印同士を結ぶ場合はその問題は起きないです。
（ユーザーが始点/終点を選べるようにするという前提を勝手に設定していました、すみません）。

宜しくお願いします。

**Comment by yoheiMune** [comment]
おはようございます。
○印での制御の件、実装いたしました。もう少し調整したい部分がありますが、このようなイメージであっていますでしょうか？
・どの要素にも左上に○印を付与
・ハイライトの○印感で矢印を引くことができる
・○印にマウスを当てると強調表示される（閲覧時）
http://pdf-anno.paint-ink.com/pages/viewer.html

また、テキストの余白も狭くしています。
合わせてご確認いただけますと幸いです。

また、以下事項は調整します。
・○印が重なる場合の表示位置調整
・○印間の矢印について、矢印の三角部分が見えるように調整

お手隙の際にご確認いただけますと幸いです。
宜しくお願いします。

**Comment by hshindo** [comment]
確認致しました．イメージは合っています．

* ○印はもっと小さくしていただけないでしょうか．
* 矢印モードになったとき，ハイライトが黄色からオレンジに変化しますが，これは不要な気がします．矢印モードに変わったとしても，そのまま黄色で良いと思います．
* 矢印ラベルのテキストボックスですが，枠の背景色を，現在の赤から白に変更できるでしょうか．また，文字色は矢印と同じ色という設定（現在の場合だと，青から赤）にしたいと思います．それから，枠の余白はまだ大きいので，これをほぼ0pxにできるでしょうか．（図を参照）

![sample1](https://cloud.githubusercontent.com/assets/6833527/19843001/ce8d5be6-9f61-11e6-8269-45c8c89e0d5d.png)

よろしくお願いします．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
修正点3つ、了解いたしました。対応してデモサイトにアップします。
引き続きどうぞ宜しくお願いします。

**Comment by yoheiMune** [comment]
お世話になっております。
以下4点修正いたしました。こちらでイメージ合っていますでしょうか？
http://pdf-anno.paint-ink.com/pages/viewer.html
1. ◯印を小さくする
2. 矢印モードの時に、ハイライトを赤くしない（矢印モードの際にUX観点より、一応マウスオーバーすると赤色が変わってマウスオーバーが有効であることを示す実装は残していますが、不要でしたらご指摘ください）
3. テキストラベルの文字色を赤、背景色を白、余白0に変更
4. ◯印が重なる場合は、重ならないように位置を調整

また、以下1点は実装はわかっているのですが、実装が少し煩雑で時間が少しかかりそうなので、後回しにさせていただくことは可能でしょうか？
===
1. ○印間の矢印について、矢印の三角部分が見えるように調整
（ベジエ曲線と◯の交点を計算して開始/終了地点を決める実装の予定）

どうぞ宜しくお願いします。

**Comment by yoheiMune** [comment]
連投失礼いたします。
また、本Issueについても、◯印を用いた実装について対応しております。
合わせてご確認いただけますと幸いです。
問題なさそうでしたら、次の #8 の実装に進めたらと思います。

どうぞ宜しくお願いします。

**Comment by hshindo** [comment]
確認致しました．これで問題なさそうです．
矢印は後回しで結構です．
次のissueをお願い致します．

**Comment by yoheiMune** [comment]
早速の確認ありがとうございます。
矢印の始点/終点の微調整については、 #13 にチケット起票しました。
引き続きどうぞ宜しくお願いします。

**Comment by hshindo** [comment]
現在は，ハイライト以外のアノテーションにも○印をつけていますが，
もし実装が複雑でないならば，rect，矢印，矢印ラベルには○印はつけず，以前のままにしておきたいと思います．
矢印のベジェ曲線，rectの枠に対するマウスオーバーや選択などのイベント処理は難しいでしょうか？
そうでなければ，○印はハイライトのみにしたいと思います．

**Comment by yoheiMune** [comment]
了解致しました。
ベジエ曲線のマウスオーバーの判定は少し実装する必要がありますが、問題ないと思います。
#8 のアノテーション編集での対象選択も、ハイライトは○印、それ以外は自身のオブジェクトをマウスオーバーのターゲットにするイメージでよろしいでしょうか？
（実装内容が似ておりますので現時点で分かってますと幸いです）

よろしくお願いします。

**Comment by hshindo** [comment]
はい、ハイライトのみ丸印、それ以外は自身のオブジェクトです。
よろしくお願いします。

**Comment by yoheiMune** [comment]
ご確認ありがとうございます、了解しました！

**Comment by yoheiMune** [comment]
お世話になっております、宗定です。
上記以降進捗の報告ができておらず申し訳ありません。
別件で作業をさせていただいておりましたため、本件の作業着手が少し遅れてしまいました。
上記の修正について今週の土曜日夜にはアップさせて頂けたら幸いです。
少し遅くなってしまい申し訳ありませんが、引き続きどうぞよろしくお願いします。

**Comment by yoheiMune** [comment]
お世話になっております、宗定です。
遅くなり申し訳ありません、以下修正を行いました。
（思ったより早く実装が終わりました）

 1. rectから○印を外し、rect領域で強調表示するように修正
 2. arrowから○印を外し、arrow領域で強調表示するように修正
 3. textから○印を外し、text領域で強調表示するように修正

http://pdf-anno.paint-ink.com/pages/viewer.html
アノテーションの実装について、アノテーションの中身を変更しましたため、一度全て削除してからテストをお願いします。お手隙の際にご確認いただけましたら幸いです。

また、こちらの対応で問題なければ次のIssueに移ります。
宜しくお願いします。

**Comment by hshindo** [comment]
有難うございます．これでＯＫです．
