### ISSUE TITLE
選択ツールの導入

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#8]
acrobatと同様に，メニューに選択ツールを導入したいと思います．
下図の黒四角で囲っているものと同様のものです．

![sample](https://cloud.githubusercontent.com/assets/6833527/19525863/55205734-965d-11e6-8c4c-857d1edec227.png)

以下の機能を考えています．acrobatの操作とおおよそ同じです．
- メニューバーの全てのボタンがオフのとき，この状態を選択モードと呼ぶことにする．
- 【アノテーションの選択化】　選択モードで，矢印or矢印ラベル，ハイライトの○印，rectのいずれかをクリックすると，そのアノテーション領域が「選択中」状態になる．（「選択中」であることがわかるように表示する）
- 【アノテーションの削除】　あるアノテーションが「選択中」のとき，バックスペースまたはdeleteキーを押すと，そのアノテーションが削除される．矢印ラベル，ハイライト，rectの３種類に対して動作する．
  矢印と矢印ラベルはセットなので，「選択中」にする，または削除するのは同時で良いです．（矢印ラベルのみ削除等はできない）
- 【Rectの移動】　選択モードのとき，マウスでrectをクリックしてドラッグすると，rectを移動させることができる．マウスをドロップすると，そこでrectが固定される．
- 【矢印の始点または終点の移動】　選択モードのとき，矢印の始点（すなわち，ハイライトの○印）をドラッグして，始点を別の場所へ移動させることができる．Invalidな場所でマウスドロップされた場合は，始点が元の位置へ戻る．終点についても同様．
- 【矢印ラベルの編集】　選択モードのとき，矢印ラベルをダブルクリックすると，矢印ラベルのテキストボックスが編集可能になり，ラベルのテキストを変更できる．

**Comment by hshindo** [comment]
acrobatの「選択中」状態の表示を例として挙げておきます．（あくまでも参考です）

上：　通常のハイライト，　下：　「選択中」の状態

![sample](https://cloud.githubusercontent.com/assets/6833527/19795896/f6bb34a6-9d1a-11e6-9761-6f8ed5c1c80b.png)

![sample1](https://cloud.githubusercontent.com/assets/6833527/19795899/f9c166e8-9d1a-11e6-9eaf-50299ce1e154.png)

**Comment by hshindo** [comment]
現在は，pdf viewerのメニューバーに，ハイライト，矢印などのボタンがあり，どれか１つがオンになっているか，または，全てがオフの状態が許容されていると思います．
これを修正して，必ずどれか１つのモードがオンの状態しか許容されないということにして，デフォルトは選択モードがオンになっていることにしたいと思います．
acrobatもそのようになっていたと思います．

**Comment by hshindo** [comment]
すみません，選択モードはデフォルトの状態なので，わざわざ選択ツールのボタンをメニューバーに入れる必要はないかもしれませんが，いかがでしょうか？

その場合だと，
> これを修正して，必ずどれか１つのモードがオンの状態しか許容されないということにして，デフォルトは選択モードがオンになっていることにしたいと思います．

これをやめて，現在のように全てのボタンがオフ，という状態を許容して，その状態のときに，選択モードのときに必要な機能を入れれば良い，ということになります．

**Comment by yoheiMune** [comment]
なるほどです！
現在の選択モード中は、PDFの文字列をマウスで選択できる程度しかやれることがないので、確かにわざわざ選択ツールボタンをメニューに入れなくても良いと思われます。
その内容で実装を進めます。

**Comment by hshindo** [comment]
少し内容を修正しましたので，reloadしてご確認ください．

**Comment by yoheiMune** [comment]
修正後の内容確認いたしました。
上記内容にて実装を進めます。
宜しくお願いします。

**Comment by yoheiMune** [comment]
お世話になっております、宗定です。
以下2点実装しました。挙動など想定通りかご確認をお願いします。
細かい点でも結構ですので、何か想定と異なる点はご指摘頂けますと幸いです。

> 【アノテーションの選択化】
> 【アノテーションの削除】

◆ 選択挙動
選択化については、各要素をクリックすると選択状態に、もう一度クリックすると非選択状態にするように実装しています。また排他的な処理は行わず、異なる要素をクリックすることで、一度に複数のアノテーションを選択状態にできるようにしています。また選択色は緑にしてみました。

◆ 削除挙動
削除については、選択されている要素（複数ある場合はそれらすべて）を削除します。また、ハイライト/矢印/テキストについては関連がある場合には、関連するものすべてを削除します。

引き続き残りの実装を行います。
どうぞ宜しくお願いします。

**Comment by hshindo** [comment]
有難うございます．確認しました．全体イメージは合っていますが，
* 矢印を削除すると，ハイライトまで削除されてしまう
という問題があるようです．ハイライトはそのまま残してください．

**Comment by yoheiMune** [comment]
早急なご確認ありがとうございます。

> 矢印を削除すると，ハイライトまで削除されてしまう

失礼致しました。こちらはハイライトを残すように修正します。

> また，一度どこかの矢印を削除したあと，どこかのハイライトをアノテーションすると，ハイライト領域のマウスオーバーのイベントが動作しない場合があります．

すみません、こちら理解できていないのですが、「どこかのハイライトをアノテーションすると」というのは、「どこかのハイライト同士を矢印でつなぐと」という意味になりますでしょうか？
矢印での関連について、始点が同じで終点が異なる2つの矢印がある場合に、各ハイライトは関連を1つのみ持つように実装しているため、関連が後勝ちとなっております。そのあたりが問題になりますでしょうか？

お手隙の際にご教授頂けますと幸いです。
宜しくお願いします。

**Comment by hshindo** [comment]
すみません，わかりにくかったと思いますが，
まず，A領域とB領域をハイライトして，その間に矢印をつなぎます．そして，矢印を選択して削除します．
すると，矢印とハイライトが全て削除されます．（上記の問題点）．
その後，A領域をもう一度ハイライトすると，Aのマウスオーバーのイベントが発生しません．
AやB以外の領域をハイライトすれば，従来通りマウスオーバーするとアクティブになるようです．

**Comment by yoheiMune** [comment]
詳細な手順ありがとうございます。
こちらでも再現確認取れました。
申し訳ありません、不具合と思います。修正します。

引き続きどうぞ宜しくお願いします。

**Comment by hshindo** [comment]
rectに関してですが，現在はrectの枠および内部でクリックすると選択された状態になっていると思います．
この場合，rectの内側に別のrectが入っていると，内側のrectを選択することができません．
rectの枠上でクリックした場合のみ，選択した状態になるように変更していただけないでしょうか．
マウスオーバーのイベントも同様です．

**Comment by yoheiMune** [comment]
rectのヒット判定の件、了解しました。
修正します！

**Comment by yoheiMune** [comment]
お世話になっております、宗定です。
以下の不備を修正いたしました。
> 矢印を削除すると，ハイライトまで削除されてしまう
> また，一度どこかの矢印を削除したあと，どこかのハイライトをアノテーションすると，ハイライト領域のマウスオーバーのイベントが動作しない場合があります．

http://pdf-anno.paint-ink.com/pages/viewer.html

お手隙の際にご確認頂けますと幸いです。
引き続き実装を進めます。
よろしくお願いします。

**Comment by yoheiMune** [comment]
また、rectのヒット判定も修正いたしました。
こちらもお手隙の際にイメージに合っているかご確認お願いできればとお思います。
http://pdf-anno.paint-ink.com/pages/viewer.html

**Comment by hshindo** [comment]
これでOKです．

**Comment by hshindo** [comment]
残るは，
【Rectの移動】
【矢印の始点または終点の移動】
【矢印ラベルの編集】
でしょうか．

**Comment by yoheiMune** [comment]
はい、残り３点これから実装します！

**Comment by hshindo** [comment]
【矢印の始点または終点の移動】は後回しにしようと思いますので，残りの２つをお願いします．

**Comment by yoheiMune** [comment]
了解致しました。
共有ありがとうございます。

**Comment by yoheiMune** [comment]
お世話になっております。
残りの下記実装を行いました。
> 【Rectの移動】
> 【矢印ラベルの編集】

http://pdf-anno.paint-ink.com/pages/viewer.html

お手隙の際にご確認頂けましたら幸いです。
よろしくお願いします。

**Comment by hshindo** [comment]
これで問題ないと思います．

**Comment by hshindo** [comment]
次のissueをお願いします．

**Comment by yoheiMune** [comment]
ご確認ありがとうございました。

**Comment by hshindo** [comment]
1ページ目でハイライトや矢印を弾き，そのあとに，２ページ目でもハイライトを行う．
次に，選択モードに切り替えると，２ページ目のハイライトは正常に動作するが，１ページ目のアノテーションは，マウスオーバー時のイベントが発生せず，選択もできません．

**Comment by yoheiMune** [comment]
不備があり申し訳ありません。
確認して対応します！

**Comment by yoheiMune** [comment]
上記のマウスオーバー時の不備について修正しました。
http://pdf-anno.paint-ink.com/pages/viewer.html

選択モード時の監視対象のアノテーションを、現在アクティブなページのみ、にしていたため上記のような挙動となっておりました。

お手隙の際にご確認お願いいたします。

**Comment by hshindo** [comment]
確認しました，これで問題ありません．

**Comment by hshindo** [comment]
rectの挙動が少しおかしいのですが，確認していただけないでしょうか．
rectを作成し，選択モードでそのrectをクリックすると，ずっとrectをドラッグしているような状態になってしまいます．

**Comment by yoheiMune** [comment]
不備ありすみません。確認して修正します！

**Comment by hshindo** [comment]
arrowを選択して削除すると，arrowのラベルも同時に削除される仕様だったと思いますが，
現状では，arrowを削除してもarrowラベルはそのまま残ってしまうという問題があるようです．
ご確認をお願い致します．

**Comment by yoheiMune** [comment]
すみません、こちらも不備があり申し訳ありません。確認して対応します。

**Comment by yoheiMune** [comment]
お世話になっております。以下2点修正致しました。
http://pdf-anno.paint-ink.com/pages/viewer.html

<1> rectをclickすると、ずっとドラッグしている状態となってしまう
<2> arrowのラベルを削除時にarrowが削除されない（その逆も然り）

不具合あり申し訳ございません。
お手隙の際にご確認お願いできますと幸いです。よろしくお願いします。

**Comment by hshindo** [comment]
確認致しました．これで問題ありません．

**Comment by yoheiMune** [comment]
確認ありがとうございました。
