### ISSUE TITLE
アノテーション情報をローカルに出力

### ISSUE THREAD

**Issue by hshindo** [pdfanno/pdfanno#9]
全体の流れ：
- ユーザーは，ブラウザの指定URLを開く．（pdf.js，その他jsファイル等が読み込まれる）
- ユーザーは，PDF（ローカル）をドラッグ＆ドロップでブラウザにロードする．
- ユーザーは，自分のアノテーション情報が保存されたローカルファイル（ex. shindo.anno）を指定して，ブラウザがそれを読み取る．shindo.annoには，複数のPDFファイルに対するアノテーション情報がJSONで格納されている．
  - チェックサム等を利用してPDFの一意性をチェック
- ユーザーは，追加のアノテーション作業を行う．アノテーションが追加されたら，その都度，ブラウザはshindo.annoを更新していく．アノテーション作業中は，ブラウザがファイルハンドルを保持して，他の人がshindo.annoを編集できないようにする．（←　要検討．バックアップファイルなどを自動で作る？）

アノテーション情報は，HTML5のFile APIを使用してローカルに保存する．
Firefox, Chromeは対応しているみたいです．
http://caniuse.com/#feat=fileapi

アノテーション情報は，JSONフォーマットを使用する．
shindo.annoの例：

``` javascript
{
  aaa.pdf: {
    last-modified: 201611070915,
    anno: [
      ["S1", x, y, w, h],
      ["S2", x, y, w, h],
      ["R1", "S1", "S2", "label"],
    ],
  },
  bbb.pdf: {
    last-modified: 201611070915,
    anno: [
      ["S1", x, y, w, h],
      ["S2", x, y, w, h],
      ["R1", "S1", "S2", "label"],
    ],
  },
}
```

**Comment by hshindo** [comment]
PDFの一意性に関しては，ひとまずファイル名でＯＫです．
File apiは，readに関してはfirefox, chromeで対応していますが，writer関連はchromeのみ，という状況でしょうか．
もしそうでしたら，上記のご提案でＯＫだと思います．

**Comment by yoheiMune** [comment]
はい、write関連はChromeのみ対応、という状況です。
ご確認ありがとうございます。それでは上記で提示させて頂きました内容にて進めます。
よろしくお願いします。

**Comment by hshindo** [comment]
JSONのダウンロードは，pdf,jsのメニューバーにダウンロードボタンを追加するような形になるでしょうか？
もしくは別の方法でしょうか？

**Comment by yoheiMune** [comment]
はい、メニューバーに格納するか、もう少し分かりやすいように、画面上にフローティングさせたボタンとして配置することをイメージしています。

**Comment by hshindo** [comment]
はい，ではメニューバーのボタン追加で問題なければ，そのようにお願い致します．

**Comment by yoheiMune** [comment]
了解致しました！

**Comment by hshindo** [comment]
実装に影響するかどうかわかりませんが，最終的には，
pdfをドラッグ＆ドロップ　→　pdf.js上でpdfのアノテーションができる
htmlをドラッグ＆ドロップ　→　htmlのアノテーションができる
というようなアプリを想定しています．

**Comment by yoheiMune** [comment]
最終アウトプットイメージ了解致しました。
共有ありがとうございます。

**Comment by hshindo** [comment]
質問なのですが，
gulp+Browserifyを使わずにwebpackだけで良い，というような記事を最近見かけますが，本プロジェクトではすべて必要なのでしょうか？
なるべく依存は少なくしたいのですが，そのあたりの構成が少し気になっています．

**Comment by yoheiMune** [comment]
今回拡張を行っている部分（pdf-annotate.jsや独自実装）は、webpackのみでビルドしています。Mozillaのpdf.jsはgulp+Browserifyをビルドに使っていて、もしpdf.jsを拡張することになると、それらも使う必要があります。

ですので、現状ですとビルドにはwebpackのみを利用しております。

**Comment by yoheiMune** [comment]
お世話になっております。
以下のシナリオまで実装しました。
このイメージで合っているかご確認お願いできますでしょうか？
> ・ユーザーは，ブラウザの指定URLを開く．（pdf.js，その他jsファイル等が読み込まれる）
> ・ユーザーは，PDF（ローカル）をドラッグ＆ドロップでブラウザにロードする．
> ・ユーザーは，自分のアノテーション情報が保存されたローカルファイル（ex. shindo.anno）を指定して，ブラウザがそれを読み取る．shindo.annoには，複数のPDFファイルに対するアノテーション情報がJSONで格納されている．

http://pdf-anno.paint-ink.com/pages/viewer2.html

アップロードされたファイルへの更新処理やダウンロード処理は未実装で、これから作ります。
どうぞよろしくお願いします。

**Comment by hshindo** [comment]
はい，これで良さそうです．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
それではこちらの内容で進めます。
よろしくお願いします。

**Comment by hshindo** [comment]
些細な点ですが，
* UPLOAD →　LOADに変更していただけますか？（サーバーにpdfをuploadしていると勘違いされないため）

**Comment by yoheiMune** [comment]
上記2点了解しました！
対応します。

**Comment by yoheiMune** [comment]
取り急ぎ上記2点を修正しました。
http://pdf-anno.paint-ink.com/pages/viewer2.html

よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．
細かい部分は私の方で修正してcommitしても良いでしょうか？

それから，pdfannoをローカル環境で動かすときのインストール方法などをREADMEに書いていただけないでしょうか？

**Comment by yoheiMune** [comment]
ご確認＆ご配慮ありがとうございます。
はい、コミットもぜひして頂けましたら非常に助かります。お手数おかけしてすみません。

確かにローカル環境で動作させる方法をどこにも記載できていないですね。申し訳ありません。
Readmeに記載してご連絡致します。

よろしくお願いします。

**Comment by yoheiMune** [comment]
開発方法についてReadmeに追記しました。
現状ですと、個人用にという感じで開発環境を作っておりましたので少し分かりづらい点があり恐縮ですが、ご確認いただけましたら幸いです。
https://github.com/pdfanno/pdfanno

よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．
これで試すことができますので，私の方でもREADMEを修正していきたいと思います．
よろしくお願い致します．

**Comment by yoheiMune** [comment]
ありがとうございます。よろしくお願いします。

**Comment by hshindo** [comment]
viewerに関してですが，現在はブラウザ画面全体を使ってviewerを表示していると思います．（viewer.html）

そうではなくて，webページにdivタグでviewerを埋め込むようにして，その中でpdf.jsがロードされるようにしても，アノテーション機能は正常に動作するでしょうか？

例えば，ブラウザの右半分にviewerを埋め込むような形にできるかどうか知りたいのですが．

**Comment by yoheiMune** [comment]
はい、そのような表示もできると思います。
必要あれば実際にデモを作ってみますが、いかがいたしましょうか？

**Comment by hshindo** [comment]
有難うございます．
ブラウザ画面の左側は，navigation barのようなものにして，現在のpdfに対するアノテーション一覧などを表示させたいと思っています．右側がpdf viewerです．
また，pdfやannotationファイルを指定するのも，navigation barで行うことにすれば，viewer2.htmlとviewer.HTMLのように２ページ作成する必要がなくなります．

もしそうしたときに，pdf.jsに追加しているハイライトや矢印などのボタンも，navigation barへ移動することは可能でしょうか？
メリットとしては，pdf.jsには何も手を加えないことになるので，pdf.jsを我々で再コンパイルせずに，そのまま配布できるのではないかと考えられます．

あくまでも案ですので，ご意見を伺いたいと思いますが，いかがでしょうか？

**Comment by yoheiMune** [comment]
はい、ハイライトや矢印などもナビゲーションビューに配置することも可能です(今はviewer.htmlに組み込んでいます)。
確かにpdf.jsに手を加えなくて良いのは非常に良いと思います。アップデートにもついていけますし。
良さそうと思います！！

**Comment by hshindo** [comment]
有難うございます．
では，一度そのような形にしてみたいと思います．
私の方で全体イメージを作成しますので，その後，上記のような形にしてみたいと思います．
ひとまず，ローカルファイルへの書き込みが出来てから変更します．
よろしくお願いします．

**Comment by yoheiMune** [comment]
了解致しました。こちらでも手隙の際にPDFJSの組み込み事例を調査してみます。よろしくお願いします。

**Comment by yoheiMune** [comment]
遅くなり申し訳ありません。
アノテーションのダウンロード機能も実装しました。
（アイコンは一旦「DL」というラベルにしました）
http://pdf-anno.paint-ink.com/pages/viewer.html

こちらで、アップロード〜アノテーション付与〜ダウンロードまで、一連の処理を行うことができると思います。
http://pdf-anno.paint-ink.com/pages/viewer2.html

イメージに合っているかご確認お願いします。
よろしくお願いします。

**Comment by hshindo** [comment]
出力されるJSONですが，もう少し人間が見やすい形で出力できるでしょうか？
http://shimz.me/blog/javascript/3783

JSON.stringify(a, null , "\t");
などで良いみたいです．

ソースファイル中に，stringifyが複数箇所あり，どれを変更すればよいのかよくわからなかったので，よろしくお願いします．

**Comment by hshindo** [comment]
出力されるJSONですが，もう少し整理して，なるべく不要な情報を削除したいと思います．

* "color"は不要です．
* "class":"Annotation","uuid": ... のような部分は何でしょうか？

このスレッドの一番はじめにあるshindo.annoの例とは異なる部分について，ご説明いただけないでしょうか？
よろしくお願いします．

**Comment by yoheiMune** [comment]
取り急ぎ、整形されたJSONが出力されるように修正しました。
参考リンクもありがとうございます。助かりました。

JSONの中身については現状、pdf-annotate.jsで使われている仕組みをそのまま利用しているため、ご提案頂いている内容とは異なっています。申し訳ありません。内容を精査して別途共有＆ご相談させてください。パッと見た感じでも`"class": "Annotation"`などは要らなさそうですね。。

よろしくお願いします。

**Comment by yoheiMune** [comment]
JSON内の情報について調査して記載しました。

 * `color` : 色を決め打ちにする場合には不要です
 * `size`：フォントサイズを決め打ち二する場合は不要です
 * `class:Annotation`：不要そうです
 * `uuid`：関連を表現したり削除する場合に、アノテーションを特定する際に使います

```
// レクトの場合
{
	"type": "area",									// アノテーション種類
	"x": 70.80000000000001,							// x座標
	"y": 60.60000000000001,							// y座標
	"width": 115.20000000000002,					// 横幅
	"height": 63.00000000000001,					// 縦幅
	"class": "Annotation",							// 不要そう
	"uuid": "dd85c0d2-ab3b-47d7-a2d8-9057d64adbf8",	// アノテーションを一意に特定するID
	"page": 1										// PDFのページ数
},

// ハイライトの場合
{
	"type": "highlight",							// アノテーション種類
	"color": "FFFF00",								// ハイライト色（→不要？）
	"rectangles": [									// ハイライトの領域（複数行などの場合は複数）
		{
			"y": 195.99375,
			"x": 273.1304443359375,
			"width": 96.13648681640626,
			"height": 9.600000000000001
		}
	],
	"class": "Annotation",
	"uuid": "3a5ffe5d-4724-4ebf-82c7-8fd0765d1612",
	"page": 1,
	"relId": "b4841a15-644b-4fe7-8a86-d0643315a6aa"	// Arrowで関連づけた場合に、arrowのIDが入る（削除時などの同期処理で利用）
},

// Arrowの場合
{
	"x1": 273.1304443359375,							// 始点x座標
	"y1": 192.99375,									// 始点y座標
	"x2": 399.44187011718753,							// 終点x座標
	"y2": 224.18437500000002,							// 終点y座標
	"type": "arrow",								
	"color": "FF0000",
	"relId": "b4841a15-644b-4fe7-8a86-d0643315a6aa",
	"class": "Annotation",
	"uuid": "2e32a002-fdd0-4061-9d76-2107ce0d0a50",
	"page": 1
},

// テキストの場合
{
	"type": "textbox",
	"size": 12,											// フォントサイズ
	"color": "#FF0000",
	"content": "これはarrow付属のテキスト",					// テキスト内容
	"x": 346.50000000000006,							// テキスト領域（x座標）
	"y": 184.8,											// テキスト領域（y座標）
	"width": 79.2,										// テキスト領域（横幅）
	"height": 12.600000000000001,						// テキスト領域（縦幅）
	"relId": "b4841a15-644b-4fe7-8a86-d0643315a6aa",	// Arrowと関連がある場合は、ArrowのID
	"class": "Annotation",
	"uuid": "7e351b3f-ee97-4106-b790-e41fecc2cffe",
	"page": 1
}
```

**Comment by hshindo** [comment]
uuid, relIdは，もう少し単純な名前を使用することは可能でしょうか？
それとも，pdf-annotator等によって勝手に決められてしまうのでしょうか？

**Comment by hshindo** [comment]
他のアノテーションツールとのcompatibleにしたいので，key/valueペアをあまり使わないほうが望ましいです．したがって，
rect:
```
{
  [ "rect", 1, 70.80000000000001, 60.60000000000001, 115.20000000000002, 63.00000000000001 ]
},
```
のようにしたいのですが，可能でしょうか？

**Comment by yoheiMune** [comment]
はい、可能です！具体的にこの互換性を！というのを頂けたらそれに合わせて作ります。

**Comment by hshindo** [comment]
例えば[brat](http://brat.nlplab.org/introduction.html)などですが，ひとまずrectは上記のようにお願いします．
ハイライトはもう少し考えさせてください．
arrowと，そのラベルは，
```
[ "relation-1", rect-id1, rect-id2, "relationのテキスト" ]
```
としてください．rect-id1, rect-id2は，rectの始点，終点のidを指します．

**Comment by yoheiMune** [comment]
上記の件、了解いたしました。
ありがとうございます。2点確認させてください。

◆単独のテキスト入力
pdfannoの場合、現在テキスト単独でも利用可能ですが、その場合には「text-1」のようなキー名でよろしいでしょうか？

◆ハイライト（span）のデータ表現
ハイライトでは複数行にまたがる場合や「あああTwitterいいい」のように日本語と英語などが混じり合う場合に、rect領域を複数持つ必要があります（PDF.jsの挙動より）。rect領域を複数もつ場合には、「span-1」の構造は`[1, [x,y,w,h], [x,y,w,h], "spanのテキスト"`のような形にさせて頂いてもよろしいでしょうか？

お手隙の際にご確認いただけましたら幸いです。よろしくお願いします。

**Comment by hshindo** [comment]
テキスト単独の場合を忘れていました．すみません．
```
{
  "text-1": [ 1, x, y, w, h ],
}
```
というような形でいかがでしょうか？フォントサイズや色は保存しなくてよいです．

spanですが，
``` [x,y,w,h], [x,y,w,h], "spanのテキスト" ```で構いません．
```
"span-1": [
    [ 1, x1, y1, w1, h1 ],
    [ 1, x2, y2, w2, h2 ],
    "spanのテキスト"
  ],
```
ということになるでしょうか．
表現形式としては，１ページの終わりから２ページの始めにかけて，一つのハイライトを付与した場合でも問題なさそうですね．
よろしくお願いします．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。「テキスト」「ハイライト」共にデータ構造了解しました。こちらで大丈夫そうです。

> １ページの終わりから２ページの始めにかけて，一つのハイライトを付与した場合

こちらは、拡張元に使っているpdf-annotate.jsがページをまたぐ処理を全くサポートしていないので、別途実装する必要があります（別チケットのページをまたぐArrowと同じような問題です）。ページをまたぐArrowのチケットに追記しますので、そちらで別途実装させてください。

よろしくお願いします。

**Comment by hshindo** [comment]
はい，わかりました．

JSONデータを読み込んだ後の処理についてですが，プログラム内部で，array[0]，array[1]などのインデックスを使いまわすと，JSON形式が変わったときに修正点が多くなってしまうので，
JSONオブジェクトを読み込んだあと，例えばrectならば，
id = array[0];
page = array[1];
x = array[2];
y = array[3];
のように名前付き変数に速やかに代入して，それらをプログラム内部で使うような実装にしておいていただけないでしょうか．

**Comment by yoheiMune** [comment]
少し遅くなり申し訳ございません。
データのエクスポート部分を実装しました。出力内容の認識があっていますかご確認お願いできますでしょうか？
http://pdf-anno.paint-ink.com/pages/viewer.html

今回の件でarrowのデータ設計を変えたため、少しお時間を頂いておりました。
また、上のご提案の内容の通りで実装させて頂いております（export内容は配列多様で、プログラム内では引き続きkey-value形式で使うようにしています）。

データのインポート部分をこれから作ります。
引き続きどうぞよろしくお願いします。

**Comment by hshindo** [comment]
確認しました．
これで問題なさそうです．ありがとうございました．
引き続きお願いします．

**Comment by yoheiMune** [comment]
確認ありがとうございます。
引き続き実装します。

**Comment by yoheiMune** [comment]
お世話になっております。インポート機能も実装しました。

○ アノテーションやPDFを読み込むページ
http://pdf-anno.paint-ink.com/pages/viewer2.html

○ PDFビュワー
http://pdf-anno.paint-ink.com/pages/viewer.html

ユーザーが色々とアノテーションを編集して、その後にDLして、その後にアノテーションを読み込むと編集したアノテーションが再現されるように実装しています。
（#8で指摘頂いている不具合はまだ存在します、申し訳ありません）

お手隙の際にご確認頂けたら幸いです。
よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．確認しました．

**Comment by hshindo** [comment]
全体のwebページについては，我々の方で作成中ですので，また別のissueとして報告致します．

**Comment by yoheiMune** [comment]
了解致しました。
ご確認ありがとうございました。
